ZFM_Loot_Crates =[
	"TKSpecialWeapons_EP1",
	"UNBasicAmmunitionBox_EP1",
	"CZBasicWeapons_EP1",
	"TKVehicleBox_EP1",
	"USVehicleBox_EP1",
	"USBasicAmmunitionBox_EP1",
	"GERBasicWeapons_EP1",
	"GuerillaCacheBox_EP1",
	"TKOrdnanceBox_EP1",
	"USSpecialWeapons_EP1"
 ];
 
 
 
 ZFM_LOOT_CONTENT_TEXT_TYPES =[
	"SNIPERS",
	"MACHINEGUNS",
	"RIFLES",
	"PISTOLS",
	"TOOLS",
	"BACKPACKS",
	"BUILDINGSUPPLIES",
	"MEDICAL"
 ];
 
// Minimum items per loot crates!
ZFM_MINIMUM_ITEMS_PER_LOOT_CRATE_DEADMEAT = 30;
ZFM_MINIMUM_ITEMS_PER_LOOT_CRATE_EASY = 35;
ZFM_MINIMUM_ITEMS_PER_LOOT_CRATE_MEDIUM = 40;
ZFM_MINIMUM_ITEMS_PER_LOOT_CRATE_HARD = 45;
ZFM_MINIMUM_ITEMS_PER_LOOT_CRATE_WAR_MACHINE = 50;